name: Keep Render App Awake

on:
  schedule:
    - cron: "*/5 * * * *"  # 5分ごとに実行

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    steps:
      - name: Send request
        run: curl -s https://travelreservation.onrender.com/ > /dev/null
